### ISSUE TITLE
Update frequency?

### ISSUE THREAD

**Issue by janvarsa** [c-type/senator_trading#1]
Thanks a lot for sharing this - just wondering if you'll be maintaining the data going forward?

**Comment by c-type** [comment]
Yes, the data is kept current. Whenever you run the `load_trades()` function (as shown in the README), the newest data is pulled from the internet.

The data actually comes from [this website](https://www.quiverquant.com/sources/senatetrading).
I cannot tell you exactly how frequent the data is updated but I think it is on the order of weeks.
